#!/usr/bin/env bash
# generate_manifest.sh
# Produz RAFAELIA_MANIFEST.json para o build atual com hashes e metadata.
# Usage: .github/scripts/generate_manifest.sh <artifact-path> <output-manifest-path>
set -euo pipefail
 
ARTIFACT=${1:-}
OUT=${2:-RAFAELIA_MANIFEST.json}
COMMIT=${GITHUB_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo "local")}
BRANCH=${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "local")}
RUN_ID=${GITHUB_RUN_ID:-local}
TIMESTAMP=$(date --iso-8601=seconds)
TOOLCHAIN="$(cc --version 2>/dev/null | head -n1 || echo 'unknown')"
OS="$(uname -s)-$(uname -m)"

if [ -z "$ARTIFACT" ]; then
  echo "Usage: $0 <artifact-path> [output-manifest-path]" >&2
  exit 2
fi
if [ ! -f "$ARTIFACT" ]; then
  echo "Artifact not found: $ARTIFACT" >&2
  exit 3
fi

# compute hashes (sha256, sha3 if available, blake3 if available)
SHA256=$(sha256sum "$ARTIFACT" | awk '{print $1}')
SHA3="$(command -v sha3sum >/dev/null 2>&1 && sha3sum "$ARTIFACT" | awk '{print $1}' || echo '')"
BLAKE3="$(command -v b3sum >/dev/null 2>&1 && b3sum "$ARTIFACT" | awk '{print $1}' || echo '')"

cat > "$OUT" <<EOF
{
  "build_id": "${RUN_ID}-${COMMIT}",
  "commit": "${COMMIT}",
  "branch": "${BRANCH}",
  "timestamp": "${TIMESTAMP}",
  "toolchain": "${TOOLCHAIN}",
  "os": "${OS}",
  "artifact": "$(basename "$ARTIFACT")",
  "artifact_path": "$(realpath "$ARTIFACT")",
  "sha256": "${SHA256}",
  "sha3": "${SHA3}",
  "blake3": "${BLAKE3}",
  "notes": "Generated by .github/scripts/generate_manifest.sh"
}
EOF

echo "Manifest written to ${OUT}"
exit 0
