/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.topjohnwu.magisk.obfuscate;

public final class R {
  public static final class string {
    public static final int dling=0x80010000;
    public static final int no_internet_msg=0x80010001;
    public static final int upgrade_msg=0x80010002;
  }
}