[package]
name = "magiskpolicy"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]
path = "lib.rs"

[features]
no-main = []

[lints]
workspace = true

[build-dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
cxx-gen = { workspace = true }

[dependencies]
base = { workspace = true }
cxx = { workspace = true }
