#!/usr/bin/env python3
"""Translate Clang's P1689 named-module dependencies into ndk-build rules."""

import argparse
import json
import shlex
import subprocess
from pathlib import Path


def write_if_changed(path: Path, text: str):
    if path.exists() and path.read_text() == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(text)
    temporary.replace(path)


def scan(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("--compiler", required=True)
    parser.add_argument("--source", required=True)
    parser.add_argument("--object", required=True)
    parser.add_argument("--module", required=True)
    parser.add_argument("--module-interface", action="store_true")
    parser.add_argument("--visible", required=True)
    parser.add_argument("flags", nargs=argparse.REMAINDER)
    config = parser.parse_args(shlex.split(args.args.read_text()))
    flags = config.flags[1:]
    command = [
        args.scanner,
        "-format=p1689",
        "--",
        config.compiler,
        *flags,
        config.source,
        "-o",
        config.object,
        "-MD",
        "-MP",
        "-MT",
        str(args.output),
        "-MF",
        str(args.output) + ".d",
    ]
    print(f"Scan modules: {config.source}", flush=True)
    result = subprocess.run(command, check=True, stdout=subprocess.PIPE, text=True)
    rules = json.loads(result.stdout)["rules"]
    if len(rules) != 1:
        raise ValueError(f"Expected one dependency rule for {config.source}")
    provides_module = bool(rules[0].get("provides"))
    if config.module_interface and not provides_module:
        raise ValueError(
            f"{config.source} is in LOCAL_MODULE_SRC_FILES but does not provide "
            "a named module or partition; put implementation units and consumers "
            "in LOCAL_SRC_FILES"
        )
    if provides_module and not config.module_interface:
        raise ValueError(
            f"{config.source} provides a named module or partition; "
            "list it in LOCAL_MODULE_SRC_FILES instead of LOCAL_SRC_FILES"
        )
    record = {
        "module": config.module,
        "visible": config.visible.split(","),
        "source": config.source,
        "rule": rules[0],
    }
    write_if_changed(args.output, json.dumps(record, sort_keys=True) + "\n")
    # A header/source can change without changing the module graph. Mark that
    # scan as complete nevertheless, so Make does not scan it on every build.
    args.output.touch()


def make_path(value: str) -> str:
    return (
        value.replace("$", "$$")
        .replace("#", "\\#")
        .replace(" ", "\\ ")
        .replace(":", "\\:")
    )


def graph(args):
    records = [
        json.loads(Path(p).read_text()) for p in args.manifest.read_text().splitlines()
    ]
    providers = {}
    objects = {}
    for record in records:
        rule = record["rule"]
        obj = rule["primary-output"]
        objects[obj] = record
        for provided in rule.get("provides", []):
            name = provided["logical-name"]
            key = (record["module"], name)
            if key in providers:
                raise ValueError(f"Duplicate module {name}: {providers[key]} and {obj}")
            providers[key] = obj

    dependencies = {}
    for obj, record in objects.items():
        imports = {}
        visible = set(record["visible"]) | {record["module"]}
        for required in record["rule"].get("requires", []):
            name = required["logical-name"]
            candidates = {
                providers[(m, name)] for m in visible if (m, name) in providers
            }
            if len(candidates) != 1:
                reason = "Missing" if not candidates else "Ambiguous"
                raise ValueError(
                    f"{reason} provider for {name}, imported by {record['source']}"
                )
            imports[name] = candidates.pop()
        dependencies[obj] = imports

    closure = {}
    visiting = set()

    def resolve(obj):
        if obj in visiting:
            raise ValueError(
                f"Cyclic module dependency involving {objects[obj]['source']}"
            )
        if obj in closure:
            return closure[obj]
        visiting.add(obj)
        imports = dict(dependencies[obj])
        for provider in dependencies[obj].values():
            for name, dependency in resolve(provider).items():
                if name in imports and imports[name] != dependency:
                    raise ValueError(f"Conflicting providers for {name} used by {obj}")
                imports[name] = dependency
        visiting.remove(obj)
        closure[obj] = imports
        return imports

    lines = ["# Generated by ndk-modules; do not edit."]
    for obj, record in objects.items():
        imports = resolve(obj)
        flags = []
        if record["rule"].get("provides"):
            pcm = make_path(obj + ".pcm")
            flags.append(f"-fmodule-output={obj}.pcm")
            lines.extend(
                [
                    f"{pcm}: {make_path(obj)}",
                    f"ifeq ($(wildcard {pcm}),)",
                    f".PHONY: {pcm}.missing",
                    f"{make_path(obj)}: {pcm}.missing",
                    "endif",
                ]
            )
        flags.extend(
            f"-fmodule-file={name}={provider}.pcm"
            for name, provider in sorted(imports.items())
        )
        rsp = make_path(obj + ".modules.rsp")
        # Use ndk-build's write-if-different response-file helper. This also
        # recreates deleted response files without needing another scan.
        flag_text = " ".join(flags).replace("$", "$$").replace(",", "$(comma)")
        lines.extend(
            [
                f"$(call generate-file-dir,{rsp}.tmp)",
                f"$(call generate-list-file,{flag_text},{rsp})",
                f"{make_path(obj)}: {rsp} "
                + " ".join(make_path(p) for p in sorted(set(imports.values()))),
            ]
        )
    write_if_changed(args.output, "\n".join(lines) + "\n")
    args.output.touch()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    scan_parser = commands.add_parser("scan")
    scan_parser.add_argument("--scanner", required=True)
    scan_parser.add_argument("--args", type=Path, required=True)
    scan_parser.add_argument("--output", type=Path, required=True)
    graph_parser = commands.add_parser("graph")
    graph_parser.add_argument("--manifest", type=Path, required=True)
    graph_parser.add_argument("--output", type=Path, required=True)
    manifest_parser = commands.add_parser("manifest")
    manifest_parser.add_argument("--output", type=Path, required=True)
    manifest_parser.add_argument("inputs", nargs="*")
    args = parser.parse_args()
    try:
        if args.command == "scan":
            scan(args)
        elif args.command == "graph":
            graph(args)
        else:
            write_if_changed(args.output, "\n".join(args.inputs) + "\n")
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"C++ modules: {error}\n")


if __name__ == "__main__":
    main()
