#!/system/bin/sh

HIDELIST=/magisk/.core/magiskhide/hidelist
PROCESS=$1
TOOLPATH=/dev/busybox

if [ ! -z "$PROCESS" ]; then
  if [ `grep -c "^$PROCESS$" $HIDELIST` -eq "0" ]; then
    echo "$PROCESS" >> $HIDELIST
    set --
    set `$TOOLPATH/ps -o pid,args | grep "$PROCESS" | grep -v grep` >/dev/null
    [ ! -z "$1" ] && kill "$1"
  fi
fi
