[package]
name = "magiskinit"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[lints]
workspace = true

[build-dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
cxx-gen = { workspace = true }

[dependencies]
base = { workspace = true }
magiskpolicy = { workspace = true, features = ["no-main"] }
cxx = { workspace = true }
num-traits = { workspace = true }
